// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "0941aff7-8e2e-4c03-89f0-348a39022b14");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 3);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1675020514);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1675020487);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1675020997);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1675021026);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1675020544);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{fd8dc219-0404-4af5-b591-1ea0b6d9a4fd}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1675020484);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{91f44f1d-a487-4341-ae6c-051a1e14a73b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1675020486);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1675020546829");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1675022346829");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1675020490022");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1675042090022");
user_pref("browser.search.region", "PK");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230112150232");
user_pref("browser.shell.defaultBrowserCheckCount", 2);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230112150232");
user_pref("browser.startup.homepage_override.mstone", "109.0");
user_pref("browser.startup.lastColdStartupCheck", 1675020997);
user_pref("browser.theme.content-theme", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1675020486405");
user_pref("distribution.iniFile.exists.appversion", "109.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "PK");
user_pref("dom.push.userAgentID", "e2f0226f26964bb1b8f8ca8a80c9c9a5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230112150232");
user_pref("extensions.lastAppVersion", "109.0");
user_pref("extensions.lastPlatformVersion", "109.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"244fd60d-854d-47fd-94ba-ac64c92ce887\",\"pictureinpicture@mozilla.org\":\"2e187be8-e1e7-41a4-94d1-f153c8fed7c6\",\"screenshots@mozilla.org\":\"012c989b-54ae-4fae-be3a-abc633df9572\",\"webcompat-reporter@mozilla.org\":\"aaa81ef0-dd20-4c8e-a048-1e1c917dfb0f\",\"webcompat@mozilla.org\":\"e1b62ddb-0d2d-42d6-93d8-61f2ff266f64\",\"default-theme@mozilla.org\":\"7760604d-bd9c-4dd1-bd4a-24a9113b2663\",\"addons-search-detection@mozilla.com\":\"1f6735c1-f6ab-4ac0-9b53-9fb901a6d998\",\"google@search.mozilla.org\":\"5a39e0dd-45ae-4de0-a691-211e34074af2\",\"amazondotcom@search.mozilla.org\":\"8e75f311-2f88-4e08-ac97-d8b3a2ae6b57\",\"wikipedia@search.mozilla.org\":\"f2f80ebb-42b4-4bec-82c1-d0f7cd9c2aa1\",\"bing@search.mozilla.org\":\"af1c1633-f7d7-45b7-9e3c-cf027743cae8\",\"ddg@search.mozilla.org\":\"98984b74-35f7-48c9-bd80-cdab1cab59bc\",\"ebay@search.mozilla.org\":\"17f85384-9f80-4908-9725-d14377c1d28e\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1675020486);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0xbeef");
user_pref("sanity-test.driver-version", "7.0.4.4605");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20230112150232");
user_pref("security.sandbox.content.tempDirSuffix", "{2caa6bf9-9307-4669-877b-f95c53cdb214}");
user_pref("toolkit.startup.last_success", 1675020996);
user_pref("toolkit.telemetry.cachedClientID", "e7e9e56a-fd1f-4bd2-8e88-7a3971db1353");
user_pref("toolkit.telemetry.previousBuildID", "20230112150232");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
